### ISSUE TITLE
Could not connect to Wifi

### ISSUE THREAD

**Issue by AndriyPopovych** [vlast3k/simple-co2-monitor-fw#8] opened 2016-04-19 07:43 UTC
After upgrading firmware version looks like impossible to connect to WiFi. Tried a several combination with factory reset, device reset.
## 

vAir found on : COM3
received:vAir CO2 Monitor: v1.11
Visit 'vair-monitor.com' for configuration details
Send Interval: -1
No WiFi configuration

received:wifi "PTN PNH","12 symbols alphanumeric and non-alphanumeric password"

Connecting to Wifi...

received:=>R>YCG5N2%8
received:
ready
received:
AT+CWMODE_DEF=1

ERROR

received:WIFI DISCONNECT

received:Could not connect to Wifi: -1

**Comment by vlast3k** [comment] 2016-04-19 09:09
Hmm i will have a look, which was your last version?
Does it work if you revert to an older version ?

**Comment by vlast3k** [comment] 2016-04-19 10:19
Can you also try the following: from the chrome app, and the input field at the bottom, type in the command and then send it
**proxy**
wait a bit - this will connect you to the wifi module
once it starts enter
**AT**
it should respond with OK, if it says ERROR then something is wrong
also try
**AT+GMR**
this should respond with the version of the wifi firmware

**Comment by AndriyPopovych** [comment] 2016-04-19 11:05
I think previous firmware version is 1.2.2, but maybe was little newer. 
Maybe you can recall this ticket https://github.com/vlast3k/simple-co2-monitor-fw/issues/7

I found that last update on thingpeak was 2 months ago. This my mistake because I forget to change password on vAir. But there is the same router with same settings.

My router wifi settings is WPA2-PSK, 802.11bgn, 6 channel, Channel Width 20MHz

## 

vAir found on : COM3
received:vAir CO2 Monitor: v1.11
Visit 'vair-monitor.com' for configuration details
Send Interval: -1
No WiFi configuration

sending: proxy
received:proxy
ESP Proxy

received:ò=>ÐRö>Q
CºG5NÖ
2%Ë8ÿ
received:¶
ready

received:WIFI DISCONNECT

sending: AT
received:AT

ERROR

sending: AT+GMR
received:AT+GMR

ERROR

received:wifi "PTN PNH","nonalphanumericpassword"
ERROR

**Comment by AndriyPopovych** [comment] 2016-04-19 11:06
In last two lines i pressed a set wifi button.

**Comment by vlast3k** [comment] 2016-04-19 11:41
Interesting :) Apparently something happened to the Wifi module.
Maybe it just needs to be reflashed, but the problem is that it is not easy to be done.
The new ones no longer use this firmware but a more stable one
I will send you a new one, when you get it please send this one back to me, i will refund you the amount for the post
is this ok ?

**Comment by AndriyPopovych** [comment] 2016-04-19 12:24
It's not a problem to send back this device. Maybe this a better time/cost solution of this problem. So I will wait for a few days in a case if some new idea will come for mind. Please write a postal address to send it back.

**Comment by vlast3k** [comment] 2016-04-19 12:44
i doubt.. at least i have no idea what caused it
i will send you the device latest on thrusday
you are still at the same address where i sent the previous one right ?

my address is
Vladimir Savchenko
bul. Tzar Boris 3, 136 A
1618 Sofia
Bulgaria

**Comment by AndriyPopovych** [comment] 2016-04-19 15:37
I at the same address.

**Comment by AndriyPopovych** [comment] 2016-04-20 16:00
After reflashing I was found that wifi and thingspeak works for firmware version 1.2.2
After reflashing I was found that wifi and thingspeak doesn't works for firmware version 1.8.1
Maybe it will help.

## 

vAir found on : COM3
received:vAir CO2 Monitor: v1.8.1
Visit 'vair-monitor.com' for configuration details

received:tskey 5XDCG112ETA7YOBG


received:wifi "PTN PNH","pass"

Connecting to Wifi...

received:=>Z>YCG5N2%M
received:
ready
received:
AT+CWMODE_DEF=1

ERROR

received:WIFI CONNECTED

received:WIFI GOT IP

received:Could not connect to Wifi: -1

**Comment by AndriyPopovych** [comment] 2016-04-20 18:09
I shall send you this device tomorrow 21.04 if you do not mind.

**Comment by vlast3k** [comment] 2016-04-20 20:04
thanks fir the info
yes this is fine
I am also plannig to send the other one tomorrow

**Comment by AndriyPopovych** [comment] 2016-04-21 09:32
http://x.megastyle.com:8000/53c1633f833b2928d9e552ca83b7e660/IMG_20160421_123032.jpg

**Comment by vlast3k** [comment] 2016-04-26 11:17
hmm what is your paypal to send you the refunt, you can send it to vlast3k at gmail dot com

**Comment by AndriyPopovych** [comment] 2016-04-26 14:59
Did you receive my device ?
Is it possible to send me a new or repaired device with wifi module ?

**Comment by AndriyPopovych** [comment] 2016-04-26 14:59
Tracking number RD180958476UA

**Comment by vlast3k** [comment] 2016-04-27 03:40
yeah..i sent it last Friday, let's see when you will get it
i sent you a new device

**Comment by vlast3k** [comment] 2016-05-09 07:25
Did you get it ? I received yours just today

**Comment by AndriyPopovych** [comment] 2016-05-09 08:02
The post office was closed due to holiday and weekends. I can get this
device tomorrow.

2016-05-09 10:25 GMT+03:00 Vladimir Savchenko notifications@github.com:

> Did you get it ? I received yours just today
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/vlast3k/simple-co2-monitor-fw/issues/8#issuecomment-217793572

## 

+380968698822
Skype: andrew-popovich

**Comment by AndriyPopovych** [comment] 2016-05-10 15:14
Looks like after using this new device the wifi is working. But looks like something wrong with thingsspeak reporting. The graph show only two points after maybe 20 minutes of working. Thingsspeak update speed interval was 60, now 10.

Graph settings:
Type: line 
Dynamic: true 
Days: 1
Results: 600
Timescale: 60

## 

vAir found on : COM3
received:vAir CO2 Monitor: v1.11
Visit 'vair-monitor.com' for configuration details
Send Interval: 60

received:Starting Wifi Module...

received:=>IvAir WiFi module v1.5

ready1

Waiting for auto-connect

received:Network is not SAP-Guest : PTN PNH
IP address: 192.168.1.43
GOT IPFOUND

TS KEY:5XDCG112ETA7YOBG

Received command: AT+CIPSTART="TCP","184.106.153.149",80
OK
Received command: AT+CIPSEND=118

> received:
> Rcommand: GET /update?key=5XDCG112ETA7YOBG&field1=1125&field2=383.9&field3=381.0&field4=417.0&field5=42.7&field6=0.0&field7=12

received:Response Code: 200
Payload: [43400]
CLOSED
Send SAP:255

TS RES: 1

received:Starting Wifi Module...

received:=>IvAir WiFi module v1.5

ready1

Waiting for auto-connect

received:Network is not SAP-Guest : PTN PNH
IP address: 192.168.1.43
GOT IPFOUND

TS KEY:5XDCG112ETA7YOBG

Received command: AT+CIPSTART="TCP","184.106.153.149",80
OK
Received command: AT+CIPSEND=118

> received:
> Rcommand: GET /update?key=5XDCG112ETA7YOBG&field1=1131&field2=383.9&field3=380.9&field4=417.0&field5=43.0&field6=3.0&field7=12

received:Response Code: 200
Payload: [43401]
CLOSED
Send SAP:255

TS RES: 1

received:wsi 1


received:wsi 10

> Starting Wifi Module...

received:=>IvAir WiFi module v1.5

ready1

Waiting for auto-connect

received:Network is not SAP-Guest : PTN PNH
IP address: 192.168.1.43
GOT IPFOUND

TS KEY:5XDCG112ETA7YOBG

Received command: AT+CIPSTART="TCP","184.106.153.149",80
OK
Received command: AT+CIPSEND=118

> received:
> Rcommand: GET /update?key=5XDCG112ETA7YOBG&field1=1134&field2=384.0&field3=380.8&field4=417.0&field5=43.3&field6=3.0&field7=12

received:Response Code: 200
Payload: [43402]
CLOSED
Send SAP:255

TS RES: 1

received:Starting Wifi Module...

received:=>IvAir WiFi module v1.5

ready1

Waiting for auto-connect

received:Network is not SAP-Guest : PTN PNH
IP address: 192.168.1.43
GOT IPFOUND

TS KEY:5XDCG112ETA7YOBG

Received command: AT+CIPSTART="TCP","184.106.153.149",80
OK
Received command: AT+CIPSEND=118

> received:
> Rcommand: GET /update?key=5XDCG112ETA7YOBG&field1=1132&field2=384.1&field3=380.8&field4=417.0&field5=43.4&field6=1.7&field7=12

received:Response Code: 200
Payload: [43403]
CLOSED
Send SAP:255

TS RES: 1

received:Starting Wifi Module...

received:=>IvAir WiFi module v1.5

ready1

Waiting for auto-connect

received:Network is not SAP-Guest : PTN PNH
IP address: 192.168.1.43
GOT IPFOUND

TS KEY:5XDCG112ETA7YOBG

Received command: AT+CIPSTART="TCP","184.106.153.149",80
OK
Received command: AT+CIPSEND=118

> received:
> Rcommand: GET /update?key=5XDCG112ETA7YOBG&field1=1126&field2=384.3&field3=381.0&field4=417.0&field5=43.5&field6=0.2&field7=12

received:Response Code: 200
Payload: [43404]
CLOSED
Send SAP:255

TS RES: 1

received:Starting Wifi Module...

received:=>IvAir WiFi module v1.5

ready1

Waiting for auto-connect

received:Network is not SAP-Guest : PTN PNH
IP address: 192.168.1.43
GOT IPFOUND

TS KEY:5XDCG112ETA7YOBG

Received command: AT+CIPSTART="TCP","184.106.153.149",80
OK
Received command: AT+CIPSEND=119

> received:
> Rcommand: GET /update?key=5XDCG112ETA7YOBG&field1=1119&field2=384.6&field3=381.2&field4=417.0&field5=43.7&field6=-3.0&field7=13

received:Response Code: 200
Payload: [43405]
CLOSED
Send SAP:255

TS RES: 1

received:Starting Wifi Module...

received:=>IvAir WiFi module v1.5

ready1

Waiting for auto-connect

received:Network is not SAP-Guest : PTN PNH
IP address: 192.168.1.43
GOT IPFOUND

TS KEY:5XDCG112ETA7YOBG

Received command: AT+CIPSTART="TCP","184.106.153.149",80
OK
Received command: AT+CIPSEND=120

> received:
> Rcommand: GET /update?key=5XDCG112ETA7YOBG&field1=1111&field2=384.9&field3=381.4&field4=417.0&field5=43.8&field6=-5.-7&field7=13

received:Response Code: 200
Payload: [43406]
CLOSED
Send SAP:255

TS RES: 1

received:Starting Wifi Module...

received:=>IvAir WiFi module v1.5

ready1

Waiting for auto-connect

received:Network is not SAP-Guest : PTN PNH
IP address: 192.168.1.43
GOT IPFOUND

TS KEY:5XDCG112ETA7YOBG

Received command: AT+CIPSTART="TCP","184.106.153.149",80
OK
Received command: AT+CIPSEND=119

> received:
> Rcommand: GET /update?key=5XDCG112ETA7YOBG&field1=1104&field2=385.2&field3=381.6&field4=417.0&field5=43.9&field6=-7.0&field7=13

received:Response Code: 200
Payload: [43407]
CLOSED
Send SAP:255

TS RES: 1

**Comment by AndriyPopovych** [comment] 2016-05-10 15:15
http://x.megastyle.com:8000/5df65cacda4348bdac4c0702a2c0a436/%D0%97%D0%BD%D1%96%D0%BC%D0%BE%D0%BA%20%D0%B5%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%20%D0%B7%202016-05-10%2018%3a10%3a02.png

**Comment by AndriyPopovych** [comment] 2016-05-10 17:19
After a few hours of working looks. 
http://x.megastyle.com:8000/6dfd483cbda5b6909def97b99c9e1eff/%D0%97%D0%BD%D1%96%D0%BC%D0%BE%D0%BA%20%D0%B5%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%20%D0%B7%202016-05-10%2020%3a16%3a40.png

**Comment by AndriyPopovych** [comment] 2016-05-12 08:38
Issue was resolved. Looks like all working fine. )

**Comment by vlast3k** [comment] 2016-05-12 09:08
Great, sorry i didn't answer earlier... the notifications from github issue
updates get somehow merged with all githubs i am following and i hven't
been looking on them for the last days

**Closed as completed** 2016-07-23 06:44 UTC
